package cit.edu.furrevercare.entity;

import com.google.cloud.Timestamp;

public class Alert {
    private String alertID; // Auto-generated by Firestore or Service
    private String petID; // Optional, could be user-level too
    private String userID;
    private String message; // e.g., "Medication 'XYZ' due in 1 hour", "Vet appointment tomorrow"
    private AlertType alertType; // Enum: REMINDER, WARNING, INFO
    private Timestamp createdAt;
    private boolean readStatus;
    private AlertSeverity severity; // Enum: LOW, MEDIUM, HIGH

    // Enum for Alert Type
    public enum AlertType {
        REMINDER, WARNING, INFO
    }

    // Enum for Alert Severity
    public enum AlertSeverity {
        LOW, MEDIUM, HIGH
    }

    // Constructors
    public Alert() {}

    public Alert(String alertID, String petID, String userID, String message, AlertType alertType, Timestamp createdAt, boolean readStatus, AlertSeverity severity) {
        this.alertID = alertID;
        this.petID = petID;
        this.userID = userID;
        this.message = message;
        this.alertType = alertType;
        this.createdAt = createdAt;
        this.readStatus = readStatus;
        this.severity = severity;
    }

    // Getters and Setters
    public String getAlertID() { return alertID; }
    public void setAlertID(String alertID) { this.alertID = alertID; }

    public String getPetID() { return petID; }
    public void setPetID(String petID) { this.petID = petID; }

    public String getUserID() { return userID; }
    public void setUserID(String userID) { this.userID = userID; }

    public String getMessage() { return message; }
    public void setMessage(String message) { this.message = message; }

    public AlertType getAlertType() { return alertType; }
    public void setAlertType(AlertType alertType) { this.alertType = alertType; }

    public Timestamp getCreatedAt() { return createdAt; }
    public void setCreatedAt(Timestamp createdAt) { this.createdAt = createdAt; }

    public boolean isReadStatus() { return readStatus; }
    public void setReadStatus(boolean readStatus) { this.readStatus = readStatus; }

    public AlertSeverity getSeverity() { return severity; }
    public void setSeverity(AlertSeverity severity) { this.severity = severity; }
}